################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CXX_SRCS += \
../Dep/panda/src/pgraph/accumulatedAttribs.cxx \
../Dep/panda/src/pgraph/alphaTestAttrib.cxx \
../Dep/panda/src/pgraph/antialiasAttrib.cxx \
../Dep/panda/src/pgraph/attribNodeRegistry.cxx \
../Dep/panda/src/pgraph/audioVolumeAttrib.cxx \
../Dep/panda/src/pgraph/auxBitplaneAttrib.cxx \
../Dep/panda/src/pgraph/auxSceneData.cxx \
../Dep/panda/src/pgraph/bamFile.cxx \
../Dep/panda/src/pgraph/billboardEffect.cxx \
../Dep/panda/src/pgraph/cacheStats.cxx \
../Dep/panda/src/pgraph/camera.cxx \
../Dep/panda/src/pgraph/clipPlaneAttrib.cxx \
../Dep/panda/src/pgraph/colorAttrib.cxx \
../Dep/panda/src/pgraph/colorBlendAttrib.cxx \
../Dep/panda/src/pgraph/colorScaleAttrib.cxx \
../Dep/panda/src/pgraph/colorWriteAttrib.cxx \
../Dep/panda/src/pgraph/compassEffect.cxx \
../Dep/panda/src/pgraph/config_pgraph.cxx \
../Dep/panda/src/pgraph/cullBin.cxx \
../Dep/panda/src/pgraph/cullBinAttrib.cxx \
../Dep/panda/src/pgraph/cullBinManager.cxx \
../Dep/panda/src/pgraph/cullFaceAttrib.cxx \
../Dep/panda/src/pgraph/cullHandler.cxx \
../Dep/panda/src/pgraph/cullPlanes.cxx \
../Dep/panda/src/pgraph/cullResult.cxx \
../Dep/panda/src/pgraph/cullTraverser.cxx \
../Dep/panda/src/pgraph/cullTraverserData.cxx \
../Dep/panda/src/pgraph/cullableObject.cxx \
../Dep/panda/src/pgraph/decalEffect.cxx \
../Dep/panda/src/pgraph/depthOffsetAttrib.cxx \
../Dep/panda/src/pgraph/depthTestAttrib.cxx \
../Dep/panda/src/pgraph/depthWriteAttrib.cxx \
../Dep/panda/src/pgraph/eventStorePandaNode.cxx \
../Dep/panda/src/pgraph/findApproxLevelEntry.cxx \
../Dep/panda/src/pgraph/findApproxPath.cxx \
../Dep/panda/src/pgraph/fog.cxx \
../Dep/panda/src/pgraph/fogAttrib.cxx \
../Dep/panda/src/pgraph/geomDrawCallbackData.cxx \
../Dep/panda/src/pgraph/geomNode.cxx \
../Dep/panda/src/pgraph/geomTransformer.cxx \
../Dep/panda/src/pgraph/internalNameCollection.cxx \
../Dep/panda/src/pgraph/lensNode.cxx \
../Dep/panda/src/pgraph/light.cxx \
../Dep/panda/src/pgraph/lightAttrib.cxx \
../Dep/panda/src/pgraph/lightRampAttrib.cxx \
../Dep/panda/src/pgraph/loader.cxx \
../Dep/panda/src/pgraph/loaderFileType.cxx \
../Dep/panda/src/pgraph/loaderFileTypeBam.cxx \
../Dep/panda/src/pgraph/loaderFileTypeRegistry.cxx \
../Dep/panda/src/pgraph/materialAttrib.cxx \
../Dep/panda/src/pgraph/materialCollection.cxx \
../Dep/panda/src/pgraph/modelFlattenRequest.cxx \
../Dep/panda/src/pgraph/modelLoadRequest.cxx \
../Dep/panda/src/pgraph/modelNode.cxx \
../Dep/panda/src/pgraph/modelPool.cxx \
../Dep/panda/src/pgraph/modelRoot.cxx \
../Dep/panda/src/pgraph/nodePath.cxx \
../Dep/panda/src/pgraph/nodePathCollection.cxx \
../Dep/panda/src/pgraph/nodePathComponent.cxx \
../Dep/panda/src/pgraph/nodePathLerps.cxx \
../Dep/panda/src/pgraph/pandaNode.cxx \
../Dep/panda/src/pgraph/pandaNodeChain.cxx \
../Dep/panda/src/pgraph/pgraph_composite.cxx \
../Dep/panda/src/pgraph/pgraph_composite1.cxx \
../Dep/panda/src/pgraph/pgraph_composite2.cxx \
../Dep/panda/src/pgraph/pgraph_composite3.cxx \
../Dep/panda/src/pgraph/pgraph_composite4.cxx \
../Dep/panda/src/pgraph/planeNode.cxx \
../Dep/panda/src/pgraph/polylightEffect.cxx \
../Dep/panda/src/pgraph/polylightNode.cxx \
../Dep/panda/src/pgraph/portalClipper.cxx \
../Dep/panda/src/pgraph/portalNode.cxx \
../Dep/panda/src/pgraph/renderAttrib.cxx \
../Dep/panda/src/pgraph/renderAttribRegistry.cxx \
../Dep/panda/src/pgraph/renderEffect.cxx \
../Dep/panda/src/pgraph/renderEffects.cxx \
../Dep/panda/src/pgraph/renderModeAttrib.cxx \
../Dep/panda/src/pgraph/renderState.cxx \
../Dep/panda/src/pgraph/rescaleNormalAttrib.cxx \
../Dep/panda/src/pgraph/sceneGraphReducer.cxx \
../Dep/panda/src/pgraph/sceneSetup.cxx \
../Dep/panda/src/pgraph/scissorAttrib.cxx \
../Dep/panda/src/pgraph/scissorEffect.cxx \
../Dep/panda/src/pgraph/shadeModelAttrib.cxx \
../Dep/panda/src/pgraph/shaderAttrib.cxx \
../Dep/panda/src/pgraph/shaderInput.cxx \
../Dep/panda/src/pgraph/shaderPool.cxx \
../Dep/panda/src/pgraph/showBoundsEffect.cxx \
../Dep/panda/src/pgraph/stateMunger.cxx \
../Dep/panda/src/pgraph/stencilAttrib.cxx \
../Dep/panda/src/pgraph/test_pgraph.cxx \
../Dep/panda/src/pgraph/texGenAttrib.cxx \
../Dep/panda/src/pgraph/texMatrixAttrib.cxx \
../Dep/panda/src/pgraph/texProjectorEffect.cxx \
../Dep/panda/src/pgraph/textureAttrib.cxx \
../Dep/panda/src/pgraph/textureStageCollection.cxx \
../Dep/panda/src/pgraph/transformState.cxx \
../Dep/panda/src/pgraph/transparencyAttrib.cxx \
../Dep/panda/src/pgraph/uvScrollNode.cxx \
../Dep/panda/src/pgraph/weakNodePath.cxx \
../Dep/panda/src/pgraph/workingNodePath.cxx 

OBJS += \
./Dep/panda/src/pgraph/accumulatedAttribs.o \
./Dep/panda/src/pgraph/alphaTestAttrib.o \
./Dep/panda/src/pgraph/antialiasAttrib.o \
./Dep/panda/src/pgraph/attribNodeRegistry.o \
./Dep/panda/src/pgraph/audioVolumeAttrib.o \
./Dep/panda/src/pgraph/auxBitplaneAttrib.o \
./Dep/panda/src/pgraph/auxSceneData.o \
./Dep/panda/src/pgraph/bamFile.o \
./Dep/panda/src/pgraph/billboardEffect.o \
./Dep/panda/src/pgraph/cacheStats.o \
./Dep/panda/src/pgraph/camera.o \
./Dep/panda/src/pgraph/clipPlaneAttrib.o \
./Dep/panda/src/pgraph/colorAttrib.o \
./Dep/panda/src/pgraph/colorBlendAttrib.o \
./Dep/panda/src/pgraph/colorScaleAttrib.o \
./Dep/panda/src/pgraph/colorWriteAttrib.o \
./Dep/panda/src/pgraph/compassEffect.o \
./Dep/panda/src/pgraph/config_pgraph.o \
./Dep/panda/src/pgraph/cullBin.o \
./Dep/panda/src/pgraph/cullBinAttrib.o \
./Dep/panda/src/pgraph/cullBinManager.o \
./Dep/panda/src/pgraph/cullFaceAttrib.o \
./Dep/panda/src/pgraph/cullHandler.o \
./Dep/panda/src/pgraph/cullPlanes.o \
./Dep/panda/src/pgraph/cullResult.o \
./Dep/panda/src/pgraph/cullTraverser.o \
./Dep/panda/src/pgraph/cullTraverserData.o \
./Dep/panda/src/pgraph/cullableObject.o \
./Dep/panda/src/pgraph/decalEffect.o \
./Dep/panda/src/pgraph/depthOffsetAttrib.o \
./Dep/panda/src/pgraph/depthTestAttrib.o \
./Dep/panda/src/pgraph/depthWriteAttrib.o \
./Dep/panda/src/pgraph/eventStorePandaNode.o \
./Dep/panda/src/pgraph/findApproxLevelEntry.o \
./Dep/panda/src/pgraph/findApproxPath.o \
./Dep/panda/src/pgraph/fog.o \
./Dep/panda/src/pgraph/fogAttrib.o \
./Dep/panda/src/pgraph/geomDrawCallbackData.o \
./Dep/panda/src/pgraph/geomNode.o \
./Dep/panda/src/pgraph/geomTransformer.o \
./Dep/panda/src/pgraph/internalNameCollection.o \
./Dep/panda/src/pgraph/lensNode.o \
./Dep/panda/src/pgraph/light.o \
./Dep/panda/src/pgraph/lightAttrib.o \
./Dep/panda/src/pgraph/lightRampAttrib.o \
./Dep/panda/src/pgraph/loader.o \
./Dep/panda/src/pgraph/loaderFileType.o \
./Dep/panda/src/pgraph/loaderFileTypeBam.o \
./Dep/panda/src/pgraph/loaderFileTypeRegistry.o \
./Dep/panda/src/pgraph/materialAttrib.o \
./Dep/panda/src/pgraph/materialCollection.o \
./Dep/panda/src/pgraph/modelFlattenRequest.o \
./Dep/panda/src/pgraph/modelLoadRequest.o \
./Dep/panda/src/pgraph/modelNode.o \
./Dep/panda/src/pgraph/modelPool.o \
./Dep/panda/src/pgraph/modelRoot.o \
./Dep/panda/src/pgraph/nodePath.o \
./Dep/panda/src/pgraph/nodePathCollection.o \
./Dep/panda/src/pgraph/nodePathComponent.o \
./Dep/panda/src/pgraph/nodePathLerps.o \
./Dep/panda/src/pgraph/pandaNode.o \
./Dep/panda/src/pgraph/pandaNodeChain.o \
./Dep/panda/src/pgraph/pgraph_composite.o \
./Dep/panda/src/pgraph/pgraph_composite1.o \
./Dep/panda/src/pgraph/pgraph_composite2.o \
./Dep/panda/src/pgraph/pgraph_composite3.o \
./Dep/panda/src/pgraph/pgraph_composite4.o \
./Dep/panda/src/pgraph/planeNode.o \
./Dep/panda/src/pgraph/polylightEffect.o \
./Dep/panda/src/pgraph/polylightNode.o \
./Dep/panda/src/pgraph/portalClipper.o \
./Dep/panda/src/pgraph/portalNode.o \
./Dep/panda/src/pgraph/renderAttrib.o \
./Dep/panda/src/pgraph/renderAttribRegistry.o \
./Dep/panda/src/pgraph/renderEffect.o \
./Dep/panda/src/pgraph/renderEffects.o \
./Dep/panda/src/pgraph/renderModeAttrib.o \
./Dep/panda/src/pgraph/renderState.o \
./Dep/panda/src/pgraph/rescaleNormalAttrib.o \
./Dep/panda/src/pgraph/sceneGraphReducer.o \
./Dep/panda/src/pgraph/sceneSetup.o \
./Dep/panda/src/pgraph/scissorAttrib.o \
./Dep/panda/src/pgraph/scissorEffect.o \
./Dep/panda/src/pgraph/shadeModelAttrib.o \
./Dep/panda/src/pgraph/shaderAttrib.o \
./Dep/panda/src/pgraph/shaderInput.o \
./Dep/panda/src/pgraph/shaderPool.o \
./Dep/panda/src/pgraph/showBoundsEffect.o \
./Dep/panda/src/pgraph/stateMunger.o \
./Dep/panda/src/pgraph/stencilAttrib.o \
./Dep/panda/src/pgraph/test_pgraph.o \
./Dep/panda/src/pgraph/texGenAttrib.o \
./Dep/panda/src/pgraph/texMatrixAttrib.o \
./Dep/panda/src/pgraph/texProjectorEffect.o \
./Dep/panda/src/pgraph/textureAttrib.o \
./Dep/panda/src/pgraph/textureStageCollection.o \
./Dep/panda/src/pgraph/transformState.o \
./Dep/panda/src/pgraph/transparencyAttrib.o \
./Dep/panda/src/pgraph/uvScrollNode.o \
./Dep/panda/src/pgraph/weakNodePath.o \
./Dep/panda/src/pgraph/workingNodePath.o 

CXX_DEPS += \
./Dep/panda/src/pgraph/accumulatedAttribs.d \
./Dep/panda/src/pgraph/alphaTestAttrib.d \
./Dep/panda/src/pgraph/antialiasAttrib.d \
./Dep/panda/src/pgraph/attribNodeRegistry.d \
./Dep/panda/src/pgraph/audioVolumeAttrib.d \
./Dep/panda/src/pgraph/auxBitplaneAttrib.d \
./Dep/panda/src/pgraph/auxSceneData.d \
./Dep/panda/src/pgraph/bamFile.d \
./Dep/panda/src/pgraph/billboardEffect.d \
./Dep/panda/src/pgraph/cacheStats.d \
./Dep/panda/src/pgraph/camera.d \
./Dep/panda/src/pgraph/clipPlaneAttrib.d \
./Dep/panda/src/pgraph/colorAttrib.d \
./Dep/panda/src/pgraph/colorBlendAttrib.d \
./Dep/panda/src/pgraph/colorScaleAttrib.d \
./Dep/panda/src/pgraph/colorWriteAttrib.d \
./Dep/panda/src/pgraph/compassEffect.d \
./Dep/panda/src/pgraph/config_pgraph.d \
./Dep/panda/src/pgraph/cullBin.d \
./Dep/panda/src/pgraph/cullBinAttrib.d \
./Dep/panda/src/pgraph/cullBinManager.d \
./Dep/panda/src/pgraph/cullFaceAttrib.d \
./Dep/panda/src/pgraph/cullHandler.d \
./Dep/panda/src/pgraph/cullPlanes.d \
./Dep/panda/src/pgraph/cullResult.d \
./Dep/panda/src/pgraph/cullTraverser.d \
./Dep/panda/src/pgraph/cullTraverserData.d \
./Dep/panda/src/pgraph/cullableObject.d \
./Dep/panda/src/pgraph/decalEffect.d \
./Dep/panda/src/pgraph/depthOffsetAttrib.d \
./Dep/panda/src/pgraph/depthTestAttrib.d \
./Dep/panda/src/pgraph/depthWriteAttrib.d \
./Dep/panda/src/pgraph/eventStorePandaNode.d \
./Dep/panda/src/pgraph/findApproxLevelEntry.d \
./Dep/panda/src/pgraph/findApproxPath.d \
./Dep/panda/src/pgraph/fog.d \
./Dep/panda/src/pgraph/fogAttrib.d \
./Dep/panda/src/pgraph/geomDrawCallbackData.d \
./Dep/panda/src/pgraph/geomNode.d \
./Dep/panda/src/pgraph/geomTransformer.d \
./Dep/panda/src/pgraph/internalNameCollection.d \
./Dep/panda/src/pgraph/lensNode.d \
./Dep/panda/src/pgraph/light.d \
./Dep/panda/src/pgraph/lightAttrib.d \
./Dep/panda/src/pgraph/lightRampAttrib.d \
./Dep/panda/src/pgraph/loader.d \
./Dep/panda/src/pgraph/loaderFileType.d \
./Dep/panda/src/pgraph/loaderFileTypeBam.d \
./Dep/panda/src/pgraph/loaderFileTypeRegistry.d \
./Dep/panda/src/pgraph/materialAttrib.d \
./Dep/panda/src/pgraph/materialCollection.d \
./Dep/panda/src/pgraph/modelFlattenRequest.d \
./Dep/panda/src/pgraph/modelLoadRequest.d \
./Dep/panda/src/pgraph/modelNode.d \
./Dep/panda/src/pgraph/modelPool.d \
./Dep/panda/src/pgraph/modelRoot.d \
./Dep/panda/src/pgraph/nodePath.d \
./Dep/panda/src/pgraph/nodePathCollection.d \
./Dep/panda/src/pgraph/nodePathComponent.d \
./Dep/panda/src/pgraph/nodePathLerps.d \
./Dep/panda/src/pgraph/pandaNode.d \
./Dep/panda/src/pgraph/pandaNodeChain.d \
./Dep/panda/src/pgraph/pgraph_composite.d \
./Dep/panda/src/pgraph/pgraph_composite1.d \
./Dep/panda/src/pgraph/pgraph_composite2.d \
./Dep/panda/src/pgraph/pgraph_composite3.d \
./Dep/panda/src/pgraph/pgraph_composite4.d \
./Dep/panda/src/pgraph/planeNode.d \
./Dep/panda/src/pgraph/polylightEffect.d \
./Dep/panda/src/pgraph/polylightNode.d \
./Dep/panda/src/pgraph/portalClipper.d \
./Dep/panda/src/pgraph/portalNode.d \
./Dep/panda/src/pgraph/renderAttrib.d \
./Dep/panda/src/pgraph/renderAttribRegistry.d \
./Dep/panda/src/pgraph/renderEffect.d \
./Dep/panda/src/pgraph/renderEffects.d \
./Dep/panda/src/pgraph/renderModeAttrib.d \
./Dep/panda/src/pgraph/renderState.d \
./Dep/panda/src/pgraph/rescaleNormalAttrib.d \
./Dep/panda/src/pgraph/sceneGraphReducer.d \
./Dep/panda/src/pgraph/sceneSetup.d \
./Dep/panda/src/pgraph/scissorAttrib.d \
./Dep/panda/src/pgraph/scissorEffect.d \
./Dep/panda/src/pgraph/shadeModelAttrib.d \
./Dep/panda/src/pgraph/shaderAttrib.d \
./Dep/panda/src/pgraph/shaderInput.d \
./Dep/panda/src/pgraph/shaderPool.d \
./Dep/panda/src/pgraph/showBoundsEffect.d \
./Dep/panda/src/pgraph/stateMunger.d \
./Dep/panda/src/pgraph/stencilAttrib.d \
./Dep/panda/src/pgraph/test_pgraph.d \
./Dep/panda/src/pgraph/texGenAttrib.d \
./Dep/panda/src/pgraph/texMatrixAttrib.d \
./Dep/panda/src/pgraph/texProjectorEffect.d \
./Dep/panda/src/pgraph/textureAttrib.d \
./Dep/panda/src/pgraph/textureStageCollection.d \
./Dep/panda/src/pgraph/transformState.d \
./Dep/panda/src/pgraph/transparencyAttrib.d \
./Dep/panda/src/pgraph/uvScrollNode.d \
./Dep/panda/src/pgraph/weakNodePath.d \
./Dep/panda/src/pgraph/workingNodePath.d 


# Each subdirectory must supply rules for building sources it contributes
Dep/panda/src/pgraph/%.o: ../Dep/panda/src/pgraph/%.cxx
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C++ Compiler'
	g++ -I"/Users/joda2/workspace/xsilium/Dep" -O2 -g -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


