################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
../Dep/Raknet/BitStream.cpp \
../Dep/Raknet/CCRakNetSlidingWindow.cpp \
../Dep/Raknet/CCRakNetUDT.cpp \
../Dep/Raknet/CheckSum.cpp \
../Dep/Raknet/CloudClient.cpp \
../Dep/Raknet/CloudCommon.cpp \
../Dep/Raknet/CloudServer.cpp \
../Dep/Raknet/CommandParserInterface.cpp \
../Dep/Raknet/ConnectionGraph2.cpp \
../Dep/Raknet/ConsoleServer.cpp \
../Dep/Raknet/DS_BytePool.cpp \
../Dep/Raknet/DS_ByteQueue.cpp \
../Dep/Raknet/DS_HuffmanEncodingTree.cpp \
../Dep/Raknet/DS_Table.cpp \
../Dep/Raknet/DataCompressor.cpp \
../Dep/Raknet/DirectoryDeltaTransfer.cpp \
../Dep/Raknet/DynDNS.cpp \
../Dep/Raknet/EmailSender.cpp \
../Dep/Raknet/EncodeClassName.cpp \
../Dep/Raknet/EpochTimeToString.cpp \
../Dep/Raknet/FileList.cpp \
../Dep/Raknet/FileListTransfer.cpp \
../Dep/Raknet/FileOperations.cpp \
../Dep/Raknet/FormatString.cpp \
../Dep/Raknet/FullyConnectedMesh2.cpp \
../Dep/Raknet/GetTime.cpp \
../Dep/Raknet/Getche.cpp \
../Dep/Raknet/Gets.cpp \
../Dep/Raknet/GridSectorizer.cpp \
../Dep/Raknet/HTTPConnection.cpp \
../Dep/Raknet/IncrementalReadInterface.cpp \
../Dep/Raknet/Itoa.cpp \
../Dep/Raknet/LinuxStrings.cpp \
../Dep/Raknet/LocklessTypes.cpp \
../Dep/Raknet/LogCommandParser.cpp \
../Dep/Raknet/MessageFilter.cpp \
../Dep/Raknet/NatPunchthroughClient.cpp \
../Dep/Raknet/NatPunchthroughServer.cpp \
../Dep/Raknet/NatTypeDetectionClient.cpp \
../Dep/Raknet/NatTypeDetectionCommon.cpp \
../Dep/Raknet/NatTypeDetectionServer.cpp \
../Dep/Raknet/NetworkIDManager.cpp \
../Dep/Raknet/NetworkIDObject.cpp \
../Dep/Raknet/PacketConsoleLogger.cpp \
../Dep/Raknet/PacketFileLogger.cpp \
../Dep/Raknet/PacketLogger.cpp \
../Dep/Raknet/PacketOutputWindowLogger.cpp \
../Dep/Raknet/PacketizedTCP.cpp \
../Dep/Raknet/PluginInterface2.cpp \
../Dep/Raknet/RPC4Plugin.cpp \
../Dep/Raknet/Rackspace.cpp \
../Dep/Raknet/RakMemoryOverride.cpp \
../Dep/Raknet/RakNetCommandParser.cpp \
../Dep/Raknet/RakNetSocket.cpp \
../Dep/Raknet/RakNetStatistics.cpp \
../Dep/Raknet/RakNetTransport2.cpp \
../Dep/Raknet/RakNetTypes.cpp \
../Dep/Raknet/RakPeer.cpp \
../Dep/Raknet/RakSleep.cpp \
../Dep/Raknet/RakString.cpp \
../Dep/Raknet/RakThread.cpp \
../Dep/Raknet/RakWString.cpp \
../Dep/Raknet/Rand.cpp \
../Dep/Raknet/ReadyEvent.cpp \
../Dep/Raknet/ReliabilityLayer.cpp \
../Dep/Raknet/ReplicaManager3.cpp \
../Dep/Raknet/Router2.cpp \
../Dep/Raknet/SHA1.cpp \
../Dep/Raknet/SecureHandshake.cpp \
../Dep/Raknet/SendToThread.cpp \
../Dep/Raknet/SignaledEvent.cpp \
../Dep/Raknet/SimpleMutex.cpp \
../Dep/Raknet/SocketLayer.cpp \
../Dep/Raknet/StringCompressor.cpp \
../Dep/Raknet/StringTable.cpp \
../Dep/Raknet/SuperFastHash.cpp \
../Dep/Raknet/TCPInterface.cpp \
../Dep/Raknet/TableSerializer.cpp \
../Dep/Raknet/TeamBalancer.cpp \
../Dep/Raknet/TelnetTransport.cpp \
../Dep/Raknet/ThreadsafePacketLogger.cpp \
../Dep/Raknet/TwoWayAuthentication.cpp \
../Dep/Raknet/UDPForwarder.cpp \
../Dep/Raknet/UDPProxyClient.cpp \
../Dep/Raknet/UDPProxyCoordinator.cpp \
../Dep/Raknet/UDPProxyServer.cpp \
../Dep/Raknet/VariableDeltaSerializer.cpp \
../Dep/Raknet/VariableListDeltaTracker.cpp \
../Dep/Raknet/VariadicSQLParser.cpp \
../Dep/Raknet/VitaIncludes.cpp \
../Dep/Raknet/WSAStartupSingleton.cpp \
../Dep/Raknet/_FindFirst.cpp \
../Dep/Raknet/gettimeofday.cpp \
../Dep/Raknet/rdlmalloc.cpp 

OBJS += \
./Dep/Raknet/BitStream.o \
./Dep/Raknet/CCRakNetSlidingWindow.o \
./Dep/Raknet/CCRakNetUDT.o \
./Dep/Raknet/CheckSum.o \
./Dep/Raknet/CloudClient.o \
./Dep/Raknet/CloudCommon.o \
./Dep/Raknet/CloudServer.o \
./Dep/Raknet/CommandParserInterface.o \
./Dep/Raknet/ConnectionGraph2.o \
./Dep/Raknet/ConsoleServer.o \
./Dep/Raknet/DS_BytePool.o \
./Dep/Raknet/DS_ByteQueue.o \
./Dep/Raknet/DS_HuffmanEncodingTree.o \
./Dep/Raknet/DS_Table.o \
./Dep/Raknet/DataCompressor.o \
./Dep/Raknet/DirectoryDeltaTransfer.o \
./Dep/Raknet/DynDNS.o \
./Dep/Raknet/EmailSender.o \
./Dep/Raknet/EncodeClassName.o \
./Dep/Raknet/EpochTimeToString.o \
./Dep/Raknet/FileList.o \
./Dep/Raknet/FileListTransfer.o \
./Dep/Raknet/FileOperations.o \
./Dep/Raknet/FormatString.o \
./Dep/Raknet/FullyConnectedMesh2.o \
./Dep/Raknet/GetTime.o \
./Dep/Raknet/Getche.o \
./Dep/Raknet/Gets.o \
./Dep/Raknet/GridSectorizer.o \
./Dep/Raknet/HTTPConnection.o \
./Dep/Raknet/IncrementalReadInterface.o \
./Dep/Raknet/Itoa.o \
./Dep/Raknet/LinuxStrings.o \
./Dep/Raknet/LocklessTypes.o \
./Dep/Raknet/LogCommandParser.o \
./Dep/Raknet/MessageFilter.o \
./Dep/Raknet/NatPunchthroughClient.o \
./Dep/Raknet/NatPunchthroughServer.o \
./Dep/Raknet/NatTypeDetectionClient.o \
./Dep/Raknet/NatTypeDetectionCommon.o \
./Dep/Raknet/NatTypeDetectionServer.o \
./Dep/Raknet/NetworkIDManager.o \
./Dep/Raknet/NetworkIDObject.o \
./Dep/Raknet/PacketConsoleLogger.o \
./Dep/Raknet/PacketFileLogger.o \
./Dep/Raknet/PacketLogger.o \
./Dep/Raknet/PacketOutputWindowLogger.o \
./Dep/Raknet/PacketizedTCP.o \
./Dep/Raknet/PluginInterface2.o \
./Dep/Raknet/RPC4Plugin.o \
./Dep/Raknet/Rackspace.o \
./Dep/Raknet/RakMemoryOverride.o \
./Dep/Raknet/RakNetCommandParser.o \
./Dep/Raknet/RakNetSocket.o \
./Dep/Raknet/RakNetStatistics.o \
./Dep/Raknet/RakNetTransport2.o \
./Dep/Raknet/RakNetTypes.o \
./Dep/Raknet/RakPeer.o \
./Dep/Raknet/RakSleep.o \
./Dep/Raknet/RakString.o \
./Dep/Raknet/RakThread.o \
./Dep/Raknet/RakWString.o \
./Dep/Raknet/Rand.o \
./Dep/Raknet/ReadyEvent.o \
./Dep/Raknet/ReliabilityLayer.o \
./Dep/Raknet/ReplicaManager3.o \
./Dep/Raknet/Router2.o \
./Dep/Raknet/SHA1.o \
./Dep/Raknet/SecureHandshake.o \
./Dep/Raknet/SendToThread.o \
./Dep/Raknet/SignaledEvent.o \
./Dep/Raknet/SimpleMutex.o \
./Dep/Raknet/SocketLayer.o \
./Dep/Raknet/StringCompressor.o \
./Dep/Raknet/StringTable.o \
./Dep/Raknet/SuperFastHash.o \
./Dep/Raknet/TCPInterface.o \
./Dep/Raknet/TableSerializer.o \
./Dep/Raknet/TeamBalancer.o \
./Dep/Raknet/TelnetTransport.o \
./Dep/Raknet/ThreadsafePacketLogger.o \
./Dep/Raknet/TwoWayAuthentication.o \
./Dep/Raknet/UDPForwarder.o \
./Dep/Raknet/UDPProxyClient.o \
./Dep/Raknet/UDPProxyCoordinator.o \
./Dep/Raknet/UDPProxyServer.o \
./Dep/Raknet/VariableDeltaSerializer.o \
./Dep/Raknet/VariableListDeltaTracker.o \
./Dep/Raknet/VariadicSQLParser.o \
./Dep/Raknet/VitaIncludes.o \
./Dep/Raknet/WSAStartupSingleton.o \
./Dep/Raknet/_FindFirst.o \
./Dep/Raknet/gettimeofday.o \
./Dep/Raknet/rdlmalloc.o 

CPP_DEPS += \
./Dep/Raknet/BitStream.d \
./Dep/Raknet/CCRakNetSlidingWindow.d \
./Dep/Raknet/CCRakNetUDT.d \
./Dep/Raknet/CheckSum.d \
./Dep/Raknet/CloudClient.d \
./Dep/Raknet/CloudCommon.d \
./Dep/Raknet/CloudServer.d \
./Dep/Raknet/CommandParserInterface.d \
./Dep/Raknet/ConnectionGraph2.d \
./Dep/Raknet/ConsoleServer.d \
./Dep/Raknet/DS_BytePool.d \
./Dep/Raknet/DS_ByteQueue.d \
./Dep/Raknet/DS_HuffmanEncodingTree.d \
./Dep/Raknet/DS_Table.d \
./Dep/Raknet/DataCompressor.d \
./Dep/Raknet/DirectoryDeltaTransfer.d \
./Dep/Raknet/DynDNS.d \
./Dep/Raknet/EmailSender.d \
./Dep/Raknet/EncodeClassName.d \
./Dep/Raknet/EpochTimeToString.d \
./Dep/Raknet/FileList.d \
./Dep/Raknet/FileListTransfer.d \
./Dep/Raknet/FileOperations.d \
./Dep/Raknet/FormatString.d \
./Dep/Raknet/FullyConnectedMesh2.d \
./Dep/Raknet/GetTime.d \
./Dep/Raknet/Getche.d \
./Dep/Raknet/Gets.d \
./Dep/Raknet/GridSectorizer.d \
./Dep/Raknet/HTTPConnection.d \
./Dep/Raknet/IncrementalReadInterface.d \
./Dep/Raknet/Itoa.d \
./Dep/Raknet/LinuxStrings.d \
./Dep/Raknet/LocklessTypes.d \
./Dep/Raknet/LogCommandParser.d \
./Dep/Raknet/MessageFilter.d \
./Dep/Raknet/NatPunchthroughClient.d \
./Dep/Raknet/NatPunchthroughServer.d \
./Dep/Raknet/NatTypeDetectionClient.d \
./Dep/Raknet/NatTypeDetectionCommon.d \
./Dep/Raknet/NatTypeDetectionServer.d \
./Dep/Raknet/NetworkIDManager.d \
./Dep/Raknet/NetworkIDObject.d \
./Dep/Raknet/PacketConsoleLogger.d \
./Dep/Raknet/PacketFileLogger.d \
./Dep/Raknet/PacketLogger.d \
./Dep/Raknet/PacketOutputWindowLogger.d \
./Dep/Raknet/PacketizedTCP.d \
./Dep/Raknet/PluginInterface2.d \
./Dep/Raknet/RPC4Plugin.d \
./Dep/Raknet/Rackspace.d \
./Dep/Raknet/RakMemoryOverride.d \
./Dep/Raknet/RakNetCommandParser.d \
./Dep/Raknet/RakNetSocket.d \
./Dep/Raknet/RakNetStatistics.d \
./Dep/Raknet/RakNetTransport2.d \
./Dep/Raknet/RakNetTypes.d \
./Dep/Raknet/RakPeer.d \
./Dep/Raknet/RakSleep.d \
./Dep/Raknet/RakString.d \
./Dep/Raknet/RakThread.d \
./Dep/Raknet/RakWString.d \
./Dep/Raknet/Rand.d \
./Dep/Raknet/ReadyEvent.d \
./Dep/Raknet/ReliabilityLayer.d \
./Dep/Raknet/ReplicaManager3.d \
./Dep/Raknet/Router2.d \
./Dep/Raknet/SHA1.d \
./Dep/Raknet/SecureHandshake.d \
./Dep/Raknet/SendToThread.d \
./Dep/Raknet/SignaledEvent.d \
./Dep/Raknet/SimpleMutex.d \
./Dep/Raknet/SocketLayer.d \
./Dep/Raknet/StringCompressor.d \
./Dep/Raknet/StringTable.d \
./Dep/Raknet/SuperFastHash.d \
./Dep/Raknet/TCPInterface.d \
./Dep/Raknet/TableSerializer.d \
./Dep/Raknet/TeamBalancer.d \
./Dep/Raknet/TelnetTransport.d \
./Dep/Raknet/ThreadsafePacketLogger.d \
./Dep/Raknet/TwoWayAuthentication.d \
./Dep/Raknet/UDPForwarder.d \
./Dep/Raknet/UDPProxyClient.d \
./Dep/Raknet/UDPProxyCoordinator.d \
./Dep/Raknet/UDPProxyServer.d \
./Dep/Raknet/VariableDeltaSerializer.d \
./Dep/Raknet/VariableListDeltaTracker.d \
./Dep/Raknet/VariadicSQLParser.d \
./Dep/Raknet/VitaIncludes.d \
./Dep/Raknet/WSAStartupSingleton.d \
./Dep/Raknet/_FindFirst.d \
./Dep/Raknet/gettimeofday.d \
./Dep/Raknet/rdlmalloc.d 


# Each subdirectory must supply rules for building sources it contributes
Dep/Raknet/%.o: ../Dep/Raknet/%.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C++ Compiler'
	g++ -I"/Users/joda2/workspace/xsilium/Dep/Raknet" -O2 -g -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


