/*
 * LoginDatabase.h
 *
 *  Created on: 18 f�vr. 2012
 *      Author: joda2
 */

/*!
 * \file LoginDatabase.h
 * \brief Login Database
 * \author joda2
 *
 */

#ifndef LOGINDATABASE_H_
#define LOGINDATABASE_H_

#include "PostgreSQLInterface/connexionDatabase.h"
#include "Singleton/Singleton.h"

enum LoginDatabaseStatements
{
	/*  Naming standard for defines:
        {DB}_{SEL/INS/UPD/DEL}_{table}_{Summary of data changed}
        When updating more than one field, consider looking at the calling function
        name for a suiting suffix.
	 */

	REALMS_DEL_IPTEMPORAIRE_SUPPRLIGNEIP,
	REALMS_SEL_IPTEMPORAIRE_LECTURENERREURS,
	REALMS_INS_IPTEMPORAIRE_STOCKAGEIPTEMPORAIRE,
	REALMS_UPD_IPTEMPORAIRE_MAJIPTEMPORAIRE,
	REALMS_SEL_IPBANNED_INFOSSURIPBANNIES,
	REALMS_INS_IPBANNED_BANIP,
	REALMS_UPD_IPBANNED_DEBANAUTOIP,
	REALMS_UPD_IPBANNED_DEBANIP,
	REALMS_SEL_ACCOUNT_RECUPINFOSCOMPTE,
	REALMS_UPD_ACCOUNT_MAJERREURSAUTH,
	REALMS_UPD_ACCOUNT_MAJLASTIP,
	REALMS_UPD_ACCOUNTBANNED_DEBANAUTOCOMPTE,
	REALMS_INS_ACCOUNTBANNED_AUTOBANCOMPTEAUTH,
	REALMS_UPD_ACCOUNTBANNED_DEBANCOMPTE,
	REALMS_SEL_LISTESERVEUR_RECUPLISTESERVEUR,
	REALMS_SEL_LISTESERVEUR_RECUPSERVEUR,
	REALMS_SEL_LISTESERVEUR_UPDATESERVEUR,
	REALMS_UPD_LISTESERVEUR_MAJCOMPTEONLINE





	/*
REALMS_INS_AVERTISSEMENTS_AJOUTAVERTISSEMENTS,
REALMS_UPD_ACCOUNT_MAJAVERTISSEMENTSCOMPTE,
REALMS_INS_ACCOUNTBANNED_AUTOBANCOMPTEPOURAVERTISSEMENTS,
REALMS_UPD_ACCOUNTACCESS_MAJGMLEVELCOMPTE,
REALMS_UPD_ACCOUNTBANNED_DEBANAUTOCOMPTE,
REALMS_INS_LISTESERVEUR_CREATIONSERVEUR,
REALMS_INS_ACCOUNTBANNED_BANCOMPTE,
REALMS_UPD_ACCOUNT_LOGCONNEXIONCOMPTE,
REALMS_UPD_ACCOUNT_MAJMAIL,
REALMS_UPD_ACCOUNT_MAJPASS,
REALMS_INS_ACCOUNTACCESS_CREATIONACCESS,
REALMS_SEL_AVERTISSEMENTS_LISTEAVERTOS,
REALMS_UPD_LISTESERVEUR_MISEONLINESERVEUR,
REALMS_UPD_LISTESERVEUR_MISEOFFLINESERVEUR,
REALMS_SEL_ACCOUNTBANNED_RECUPDATEFINBANCOMPTE

	 */

};




/*! \class LoginDatabase
 * \brief
 *
 */

class LoginDatabase : public Singleton<LoginDatabase>, public connexionDatabase {

	friend class Singleton<LoginDatabase>;


public:

	/*!
	 *  \brief Constructeur
	 *
	 *  Constructeur de la classe LoginDatabase
	 *
	 *  \param
	 */
	LoginDatabase();

	/*!
	 *  \brief Destructeur
	 *
	 *  Destructeur de la classe LoginDatabase
	 *
	 *  \param
	 */


	virtual ~LoginDatabase();

	void connexionDB(std::string infoString);

private:


};

#endif /* LOGINDATABASE_H_ */
