/*
 * PersoDatabase.h
 *
 *  Created on: 25 avril. 2013
 *      Author: nico
 */

/*!
 * \file GPersoDatabase.h
 * \brief Login Database
 * \author joda2
 *
 */

#ifndef LOGINDATABASE_H_
#define LOGINDATABASE_H_

#include "PostgreSQLInterface/connexionDatabase.h"
#include "Structure/Server.h"
#include "Singleton/Singleton.h"

enum LoginDatabaseStatements
{
    /*  Naming standard for defines:
        {DB}_{SEL/INS/UPD/DEL}_{table}_{Summary of data changed}
        When updating more than one field, consider looking at the calling function
        name for a suiting suffix.
    */

ROYAUME_INS_TICKETRUBRIQUE_CREERUBRIQUE,
ROYAUME_UPD_TICKETRUBRIQUE_SUPPRRUBRIQUE,
ROYAUME_UPD_TICKETRUBRIQUE_REACTRUBRIQUE,
ROYAUME_UPD_TICKETRUBRIQUE_MODNOM,
ROYAUME_INS_TICKETSOUSRUBRIQUE1_CREESOUSRUBRIQUE1,
ROYAUME_UPD_TICKETSOUSRUBRIQUE1_SUPPRSOUSRUBRIQUE1,
ROYAUME_UPD_TICKETSOUSRUBRIQUE1_REACTSOUSRUBRIQUE1,
ROYAUME_UPD_TICKETSOUSRUBRIQUE1_MODNOM,
ROYAUME_UPD_TICKETSOUSRUBRIQUE1_MODRUBRIQUE,
ROYAUME_INS_TICKETSOUSRUBRIQUE2_CREESOUSRUBRIQUE2,
ROYAUME_UPD_TICKETSOUSRUBRIQUE2_SUPPRSOUSRUBRIQUE2,
ROYAUME_UPD_TICKETSOUSRUBRIQUE2_REACTSOUSRUBRIQUE2,
ROYAUME_UPD_TICKETSOUSRUBRIQUE2_MODNOM,
ROYAUME_UPD_TICKETSOUSRUBRIQUE2_MODSOUSRUBRIQUE1,
ROYAUME_INS_TICKETTYPEETAT_CREEETAT,
ROYAUME_UPD_TICKETTYPEETAT_SUPPRETAT,
ROYAUME_UPD_TICKETTYPEETAT_REACTETAT,
ROYAUME_UPD_TICKETTYPEETAT_MODNOM,
ROYAUME_INS_TICKET_CREETICKET,
ROYAUME_SEL_TICKET_LISTETICKETS,
ROYAUME_SEL_TICKET_LISTETICKETSEXPEDITEUR,
ROYAUME_SEL_TICKET_DETAILSTICKET,
ROYAUME_SEL_TICKET_LISTETICKETSRUBRIQUE,
ROYAUME_SEL_TICKET_LISTETICKETSSOUSRUBRIQUE1,
ROYAUME_SEL_TICKET_LISTETICKETSSOUSRUBRIQUE2,
ROYAUME_UPD_TICKET_MAJTICKET,
ROYAUME_UPD_TICKET_DEPLACETICKET,
ROYAUME_DEL_TICKET_SUPPRTICKET,
ROYAUME_SEL_TICKETRUBRIQUE_LISTERUBRIQUESACTIF,
ROYAUME_SEL_TICKETRUBRIQUE_LISTERUBRIQUESSUPPR,
ROYAUME_SEL_TICKETSOUSRUBRIQUE1_LISTESOUSRUBRIQUE1ACTIF,
ROYAUME_SEL_TICKETSOUSRUBRIQUE1_LISTESOUSRUBRIQUE1SUPPR,
ROYAUME_SEL_TICKETSOUSRUBRIQUE2_LISTESOUSRUBRIQUE2ACTIF,
ROYAUME_SEL_TICKETSOUSRUBRIQUE2_LISTESOUSRUBRIQUE2SUPPR,

};


  /*! \class LoginDatabase
   * \brief
   *
   */

class PersoDatabase : public Singleton<PersoDatabase>, public connexionDatabase {

	friend class Singleton<PersoDatabase>;


public:

	/*!
	 *  \brief Constructeur
     *
	 *  Constructeur de la classe LoginDatabase
     *
     *  \param
     */
	PersoDatabase();

    /*!
     *  \brief Destructeur
     *
     *  Destructeur de la classe LoginDatabase
     *
     *  \param
     */


	virtual ~PersoDatabase();

	void connexionDB(std::string infoString);

private:


};

#endif /* LOGINDATABASE_H_ */
