################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CXX_SRCS += \
../Dep/panda/src/physx/config_physx.cxx \
../Dep/panda/src/physx/physxActor.cxx \
../Dep/panda/src/physx/physxActorDesc.cxx \
../Dep/panda/src/physx/physxBodyDesc.cxx \
../Dep/panda/src/physx/physxBounds3.cxx \
../Dep/panda/src/physx/physxBox.cxx \
../Dep/panda/src/physx/physxBoxController.cxx \
../Dep/panda/src/physx/physxBoxControllerDesc.cxx \
../Dep/panda/src/physx/physxBoxForceFieldShape.cxx \
../Dep/panda/src/physx/physxBoxForceFieldShapeDesc.cxx \
../Dep/panda/src/physx/physxBoxShape.cxx \
../Dep/panda/src/physx/physxBoxShapeDesc.cxx \
../Dep/panda/src/physx/physxCapsule.cxx \
../Dep/panda/src/physx/physxCapsuleController.cxx \
../Dep/panda/src/physx/physxCapsuleControllerDesc.cxx \
../Dep/panda/src/physx/physxCapsuleForceFieldShape.cxx \
../Dep/panda/src/physx/physxCapsuleForceFieldShapeDesc.cxx \
../Dep/panda/src/physx/physxCapsuleShape.cxx \
../Dep/panda/src/physx/physxCapsuleShapeDesc.cxx \
../Dep/panda/src/physx/physxCloth.cxx \
../Dep/panda/src/physx/physxClothDesc.cxx \
../Dep/panda/src/physx/physxClothMesh.cxx \
../Dep/panda/src/physx/physxClothMeshDesc.cxx \
../Dep/panda/src/physx/physxClothNode.cxx \
../Dep/panda/src/physx/physxConstraintDominance.cxx \
../Dep/panda/src/physx/physxContactPair.cxx \
../Dep/panda/src/physx/physxContactPoint.cxx \
../Dep/panda/src/physx/physxContactReport.cxx \
../Dep/panda/src/physx/physxController.cxx \
../Dep/panda/src/physx/physxControllerDesc.cxx \
../Dep/panda/src/physx/physxControllerReport.cxx \
../Dep/panda/src/physx/physxConvexForceFieldShape.cxx \
../Dep/panda/src/physx/physxConvexForceFieldShapeDesc.cxx \
../Dep/panda/src/physx/physxConvexMesh.cxx \
../Dep/panda/src/physx/physxConvexMeshDesc.cxx \
../Dep/panda/src/physx/physxConvexShape.cxx \
../Dep/panda/src/physx/physxConvexShapeDesc.cxx \
../Dep/panda/src/physx/physxCylindricalJoint.cxx \
../Dep/panda/src/physx/physxCylindricalJointDesc.cxx \
../Dep/panda/src/physx/physxD6Joint.cxx \
../Dep/panda/src/physx/physxD6JointDesc.cxx \
../Dep/panda/src/physx/physxDebugGeomNode.cxx \
../Dep/panda/src/physx/physxDistanceJoint.cxx \
../Dep/panda/src/physx/physxDistanceJointDesc.cxx \
../Dep/panda/src/physx/physxEnums.cxx \
../Dep/panda/src/physx/physxFileStream.cxx \
../Dep/panda/src/physx/physxFixedJoint.cxx \
../Dep/panda/src/physx/physxFixedJointDesc.cxx \
../Dep/panda/src/physx/physxForceField.cxx \
../Dep/panda/src/physx/physxForceFieldDesc.cxx \
../Dep/panda/src/physx/physxForceFieldShape.cxx \
../Dep/panda/src/physx/physxForceFieldShapeDesc.cxx \
../Dep/panda/src/physx/physxForceFieldShapeGroup.cxx \
../Dep/panda/src/physx/physxForceFieldShapeGroupDesc.cxx \
../Dep/panda/src/physx/physxGroupsMask.cxx \
../Dep/panda/src/physx/physxHeightField.cxx \
../Dep/panda/src/physx/physxHeightFieldDesc.cxx \
../Dep/panda/src/physx/physxHeightFieldShape.cxx \
../Dep/panda/src/physx/physxHeightFieldShapeDesc.cxx \
../Dep/panda/src/physx/physxJoint.cxx \
../Dep/panda/src/physx/physxJointDesc.cxx \
../Dep/panda/src/physx/physxJointDriveDesc.cxx \
../Dep/panda/src/physx/physxJointLimitDesc.cxx \
../Dep/panda/src/physx/physxJointLimitSoftDesc.cxx \
../Dep/panda/src/physx/physxKitchen.cxx \
../Dep/panda/src/physx/physxLinearInterpolationValues.cxx \
../Dep/panda/src/physx/physxManager.cxx \
../Dep/panda/src/physx/physxMask.cxx \
../Dep/panda/src/physx/physxMaterial.cxx \
../Dep/panda/src/physx/physxMaterialDesc.cxx \
../Dep/panda/src/physx/physxMemoryReadBuffer.cxx \
../Dep/panda/src/physx/physxMemoryWriteBuffer.cxx \
../Dep/panda/src/physx/physxMeshHash.cxx \
../Dep/panda/src/physx/physxMeshPool.cxx \
../Dep/panda/src/physx/physxMotorDesc.cxx \
../Dep/panda/src/physx/physxObject.cxx \
../Dep/panda/src/physx/physxObjectCollection.cxx \
../Dep/panda/src/physx/physxOverlapReport.cxx \
../Dep/panda/src/physx/physxPlane.cxx \
../Dep/panda/src/physx/physxPlaneShape.cxx \
../Dep/panda/src/physx/physxPlaneShapeDesc.cxx \
../Dep/panda/src/physx/physxPointInPlaneJoint.cxx \
../Dep/panda/src/physx/physxPointInPlaneJointDesc.cxx \
../Dep/panda/src/physx/physxPointOnLineJoint.cxx \
../Dep/panda/src/physx/physxPointOnLineJointDesc.cxx \
../Dep/panda/src/physx/physxPrismaticJoint.cxx \
../Dep/panda/src/physx/physxPrismaticJointDesc.cxx \
../Dep/panda/src/physx/physxPulleyJoint.cxx \
../Dep/panda/src/physx/physxPulleyJointDesc.cxx \
../Dep/panda/src/physx/physxRay.cxx \
../Dep/panda/src/physx/physxRaycastHit.cxx \
../Dep/panda/src/physx/physxRaycastReport.cxx \
../Dep/panda/src/physx/physxRevoluteJoint.cxx \
../Dep/panda/src/physx/physxRevoluteJointDesc.cxx \
../Dep/panda/src/physx/physxScene.cxx \
../Dep/panda/src/physx/physxSceneDesc.cxx \
../Dep/panda/src/physx/physxSceneStats2.cxx \
../Dep/panda/src/physx/physxSegment.cxx \
../Dep/panda/src/physx/physxShape.cxx \
../Dep/panda/src/physx/physxShapeDesc.cxx \
../Dep/panda/src/physx/physxSoftBody.cxx \
../Dep/panda/src/physx/physxSoftBodyDesc.cxx \
../Dep/panda/src/physx/physxSoftBodyMesh.cxx \
../Dep/panda/src/physx/physxSoftBodyMeshDesc.cxx \
../Dep/panda/src/physx/physxSoftBodyNode.cxx \
../Dep/panda/src/physx/physxSphere.cxx \
../Dep/panda/src/physx/physxSphereForceFieldShape.cxx \
../Dep/panda/src/physx/physxSphereForceFieldShapeDesc.cxx \
../Dep/panda/src/physx/physxSphereShape.cxx \
../Dep/panda/src/physx/physxSphereShapeDesc.cxx \
../Dep/panda/src/physx/physxSphericalJoint.cxx \
../Dep/panda/src/physx/physxSphericalJointDesc.cxx \
../Dep/panda/src/physx/physxSpringDesc.cxx \
../Dep/panda/src/physx/physxTriangleMesh.cxx \
../Dep/panda/src/physx/physxTriangleMeshDesc.cxx \
../Dep/panda/src/physx/physxTriangleMeshShape.cxx \
../Dep/panda/src/physx/physxTriangleMeshShapeDesc.cxx \
../Dep/panda/src/physx/physxTriggerReport.cxx \
../Dep/panda/src/physx/physxUtilLib.cxx \
../Dep/panda/src/physx/physxVehicle.cxx \
../Dep/panda/src/physx/physxVehicleDesc.cxx \
../Dep/panda/src/physx/physxWheel.cxx \
../Dep/panda/src/physx/physxWheelDesc.cxx \
../Dep/panda/src/physx/physxWheelShape.cxx \
../Dep/panda/src/physx/physxWheelShapeDesc.cxx \
../Dep/panda/src/physx/physx_composite.cxx 

OBJS += \
./Dep/panda/src/physx/config_physx.o \
./Dep/panda/src/physx/physxActor.o \
./Dep/panda/src/physx/physxActorDesc.o \
./Dep/panda/src/physx/physxBodyDesc.o \
./Dep/panda/src/physx/physxBounds3.o \
./Dep/panda/src/physx/physxBox.o \
./Dep/panda/src/physx/physxBoxController.o \
./Dep/panda/src/physx/physxBoxControllerDesc.o \
./Dep/panda/src/physx/physxBoxForceFieldShape.o \
./Dep/panda/src/physx/physxBoxForceFieldShapeDesc.o \
./Dep/panda/src/physx/physxBoxShape.o \
./Dep/panda/src/physx/physxBoxShapeDesc.o \
./Dep/panda/src/physx/physxCapsule.o \
./Dep/panda/src/physx/physxCapsuleController.o \
./Dep/panda/src/physx/physxCapsuleControllerDesc.o \
./Dep/panda/src/physx/physxCapsuleForceFieldShape.o \
./Dep/panda/src/physx/physxCapsuleForceFieldShapeDesc.o \
./Dep/panda/src/physx/physxCapsuleShape.o \
./Dep/panda/src/physx/physxCapsuleShapeDesc.o \
./Dep/panda/src/physx/physxCloth.o \
./Dep/panda/src/physx/physxClothDesc.o \
./Dep/panda/src/physx/physxClothMesh.o \
./Dep/panda/src/physx/physxClothMeshDesc.o \
./Dep/panda/src/physx/physxClothNode.o \
./Dep/panda/src/physx/physxConstraintDominance.o \
./Dep/panda/src/physx/physxContactPair.o \
./Dep/panda/src/physx/physxContactPoint.o \
./Dep/panda/src/physx/physxContactReport.o \
./Dep/panda/src/physx/physxController.o \
./Dep/panda/src/physx/physxControllerDesc.o \
./Dep/panda/src/physx/physxControllerReport.o \
./Dep/panda/src/physx/physxConvexForceFieldShape.o \
./Dep/panda/src/physx/physxConvexForceFieldShapeDesc.o \
./Dep/panda/src/physx/physxConvexMesh.o \
./Dep/panda/src/physx/physxConvexMeshDesc.o \
./Dep/panda/src/physx/physxConvexShape.o \
./Dep/panda/src/physx/physxConvexShapeDesc.o \
./Dep/panda/src/physx/physxCylindricalJoint.o \
./Dep/panda/src/physx/physxCylindricalJointDesc.o \
./Dep/panda/src/physx/physxD6Joint.o \
./Dep/panda/src/physx/physxD6JointDesc.o \
./Dep/panda/src/physx/physxDebugGeomNode.o \
./Dep/panda/src/physx/physxDistanceJoint.o \
./Dep/panda/src/physx/physxDistanceJointDesc.o \
./Dep/panda/src/physx/physxEnums.o \
./Dep/panda/src/physx/physxFileStream.o \
./Dep/panda/src/physx/physxFixedJoint.o \
./Dep/panda/src/physx/physxFixedJointDesc.o \
./Dep/panda/src/physx/physxForceField.o \
./Dep/panda/src/physx/physxForceFieldDesc.o \
./Dep/panda/src/physx/physxForceFieldShape.o \
./Dep/panda/src/physx/physxForceFieldShapeDesc.o \
./Dep/panda/src/physx/physxForceFieldShapeGroup.o \
./Dep/panda/src/physx/physxForceFieldShapeGroupDesc.o \
./Dep/panda/src/physx/physxGroupsMask.o \
./Dep/panda/src/physx/physxHeightField.o \
./Dep/panda/src/physx/physxHeightFieldDesc.o \
./Dep/panda/src/physx/physxHeightFieldShape.o \
./Dep/panda/src/physx/physxHeightFieldShapeDesc.o \
./Dep/panda/src/physx/physxJoint.o \
./Dep/panda/src/physx/physxJointDesc.o \
./Dep/panda/src/physx/physxJointDriveDesc.o \
./Dep/panda/src/physx/physxJointLimitDesc.o \
./Dep/panda/src/physx/physxJointLimitSoftDesc.o \
./Dep/panda/src/physx/physxKitchen.o \
./Dep/panda/src/physx/physxLinearInterpolationValues.o \
./Dep/panda/src/physx/physxManager.o \
./Dep/panda/src/physx/physxMask.o \
./Dep/panda/src/physx/physxMaterial.o \
./Dep/panda/src/physx/physxMaterialDesc.o \
./Dep/panda/src/physx/physxMemoryReadBuffer.o \
./Dep/panda/src/physx/physxMemoryWriteBuffer.o \
./Dep/panda/src/physx/physxMeshHash.o \
./Dep/panda/src/physx/physxMeshPool.o \
./Dep/panda/src/physx/physxMotorDesc.o \
./Dep/panda/src/physx/physxObject.o \
./Dep/panda/src/physx/physxObjectCollection.o \
./Dep/panda/src/physx/physxOverlapReport.o \
./Dep/panda/src/physx/physxPlane.o \
./Dep/panda/src/physx/physxPlaneShape.o \
./Dep/panda/src/physx/physxPlaneShapeDesc.o \
./Dep/panda/src/physx/physxPointInPlaneJoint.o \
./Dep/panda/src/physx/physxPointInPlaneJointDesc.o \
./Dep/panda/src/physx/physxPointOnLineJoint.o \
./Dep/panda/src/physx/physxPointOnLineJointDesc.o \
./Dep/panda/src/physx/physxPrismaticJoint.o \
./Dep/panda/src/physx/physxPrismaticJointDesc.o \
./Dep/panda/src/physx/physxPulleyJoint.o \
./Dep/panda/src/physx/physxPulleyJointDesc.o \
./Dep/panda/src/physx/physxRay.o \
./Dep/panda/src/physx/physxRaycastHit.o \
./Dep/panda/src/physx/physxRaycastReport.o \
./Dep/panda/src/physx/physxRevoluteJoint.o \
./Dep/panda/src/physx/physxRevoluteJointDesc.o \
./Dep/panda/src/physx/physxScene.o \
./Dep/panda/src/physx/physxSceneDesc.o \
./Dep/panda/src/physx/physxSceneStats2.o \
./Dep/panda/src/physx/physxSegment.o \
./Dep/panda/src/physx/physxShape.o \
./Dep/panda/src/physx/physxShapeDesc.o \
./Dep/panda/src/physx/physxSoftBody.o \
./Dep/panda/src/physx/physxSoftBodyDesc.o \
./Dep/panda/src/physx/physxSoftBodyMesh.o \
./Dep/panda/src/physx/physxSoftBodyMeshDesc.o \
./Dep/panda/src/physx/physxSoftBodyNode.o \
./Dep/panda/src/physx/physxSphere.o \
./Dep/panda/src/physx/physxSphereForceFieldShape.o \
./Dep/panda/src/physx/physxSphereForceFieldShapeDesc.o \
./Dep/panda/src/physx/physxSphereShape.o \
./Dep/panda/src/physx/physxSphereShapeDesc.o \
./Dep/panda/src/physx/physxSphericalJoint.o \
./Dep/panda/src/physx/physxSphericalJointDesc.o \
./Dep/panda/src/physx/physxSpringDesc.o \
./Dep/panda/src/physx/physxTriangleMesh.o \
./Dep/panda/src/physx/physxTriangleMeshDesc.o \
./Dep/panda/src/physx/physxTriangleMeshShape.o \
./Dep/panda/src/physx/physxTriangleMeshShapeDesc.o \
./Dep/panda/src/physx/physxTriggerReport.o \
./Dep/panda/src/physx/physxUtilLib.o \
./Dep/panda/src/physx/physxVehicle.o \
./Dep/panda/src/physx/physxVehicleDesc.o \
./Dep/panda/src/physx/physxWheel.o \
./Dep/panda/src/physx/physxWheelDesc.o \
./Dep/panda/src/physx/physxWheelShape.o \
./Dep/panda/src/physx/physxWheelShapeDesc.o \
./Dep/panda/src/physx/physx_composite.o 

CXX_DEPS += \
./Dep/panda/src/physx/config_physx.d \
./Dep/panda/src/physx/physxActor.d \
./Dep/panda/src/physx/physxActorDesc.d \
./Dep/panda/src/physx/physxBodyDesc.d \
./Dep/panda/src/physx/physxBounds3.d \
./Dep/panda/src/physx/physxBox.d \
./Dep/panda/src/physx/physxBoxController.d \
./Dep/panda/src/physx/physxBoxControllerDesc.d \
./Dep/panda/src/physx/physxBoxForceFieldShape.d \
./Dep/panda/src/physx/physxBoxForceFieldShapeDesc.d \
./Dep/panda/src/physx/physxBoxShape.d \
./Dep/panda/src/physx/physxBoxShapeDesc.d \
./Dep/panda/src/physx/physxCapsule.d \
./Dep/panda/src/physx/physxCapsuleController.d \
./Dep/panda/src/physx/physxCapsuleControllerDesc.d \
./Dep/panda/src/physx/physxCapsuleForceFieldShape.d \
./Dep/panda/src/physx/physxCapsuleForceFieldShapeDesc.d \
./Dep/panda/src/physx/physxCapsuleShape.d \
./Dep/panda/src/physx/physxCapsuleShapeDesc.d \
./Dep/panda/src/physx/physxCloth.d \
./Dep/panda/src/physx/physxClothDesc.d \
./Dep/panda/src/physx/physxClothMesh.d \
./Dep/panda/src/physx/physxClothMeshDesc.d \
./Dep/panda/src/physx/physxClothNode.d \
./Dep/panda/src/physx/physxConstraintDominance.d \
./Dep/panda/src/physx/physxContactPair.d \
./Dep/panda/src/physx/physxContactPoint.d \
./Dep/panda/src/physx/physxContactReport.d \
./Dep/panda/src/physx/physxController.d \
./Dep/panda/src/physx/physxControllerDesc.d \
./Dep/panda/src/physx/physxControllerReport.d \
./Dep/panda/src/physx/physxConvexForceFieldShape.d \
./Dep/panda/src/physx/physxConvexForceFieldShapeDesc.d \
./Dep/panda/src/physx/physxConvexMesh.d \
./Dep/panda/src/physx/physxConvexMeshDesc.d \
./Dep/panda/src/physx/physxConvexShape.d \
./Dep/panda/src/physx/physxConvexShapeDesc.d \
./Dep/panda/src/physx/physxCylindricalJoint.d \
./Dep/panda/src/physx/physxCylindricalJointDesc.d \
./Dep/panda/src/physx/physxD6Joint.d \
./Dep/panda/src/physx/physxD6JointDesc.d \
./Dep/panda/src/physx/physxDebugGeomNode.d \
./Dep/panda/src/physx/physxDistanceJoint.d \
./Dep/panda/src/physx/physxDistanceJointDesc.d \
./Dep/panda/src/physx/physxEnums.d \
./Dep/panda/src/physx/physxFileStream.d \
./Dep/panda/src/physx/physxFixedJoint.d \
./Dep/panda/src/physx/physxFixedJointDesc.d \
./Dep/panda/src/physx/physxForceField.d \
./Dep/panda/src/physx/physxForceFieldDesc.d \
./Dep/panda/src/physx/physxForceFieldShape.d \
./Dep/panda/src/physx/physxForceFieldShapeDesc.d \
./Dep/panda/src/physx/physxForceFieldShapeGroup.d \
./Dep/panda/src/physx/physxForceFieldShapeGroupDesc.d \
./Dep/panda/src/physx/physxGroupsMask.d \
./Dep/panda/src/physx/physxHeightField.d \
./Dep/panda/src/physx/physxHeightFieldDesc.d \
./Dep/panda/src/physx/physxHeightFieldShape.d \
./Dep/panda/src/physx/physxHeightFieldShapeDesc.d \
./Dep/panda/src/physx/physxJoint.d \
./Dep/panda/src/physx/physxJointDesc.d \
./Dep/panda/src/physx/physxJointDriveDesc.d \
./Dep/panda/src/physx/physxJointLimitDesc.d \
./Dep/panda/src/physx/physxJointLimitSoftDesc.d \
./Dep/panda/src/physx/physxKitchen.d \
./Dep/panda/src/physx/physxLinearInterpolationValues.d \
./Dep/panda/src/physx/physxManager.d \
./Dep/panda/src/physx/physxMask.d \
./Dep/panda/src/physx/physxMaterial.d \
./Dep/panda/src/physx/physxMaterialDesc.d \
./Dep/panda/src/physx/physxMemoryReadBuffer.d \
./Dep/panda/src/physx/physxMemoryWriteBuffer.d \
./Dep/panda/src/physx/physxMeshHash.d \
./Dep/panda/src/physx/physxMeshPool.d \
./Dep/panda/src/physx/physxMotorDesc.d \
./Dep/panda/src/physx/physxObject.d \
./Dep/panda/src/physx/physxObjectCollection.d \
./Dep/panda/src/physx/physxOverlapReport.d \
./Dep/panda/src/physx/physxPlane.d \
./Dep/panda/src/physx/physxPlaneShape.d \
./Dep/panda/src/physx/physxPlaneShapeDesc.d \
./Dep/panda/src/physx/physxPointInPlaneJoint.d \
./Dep/panda/src/physx/physxPointInPlaneJointDesc.d \
./Dep/panda/src/physx/physxPointOnLineJoint.d \
./Dep/panda/src/physx/physxPointOnLineJointDesc.d \
./Dep/panda/src/physx/physxPrismaticJoint.d \
./Dep/panda/src/physx/physxPrismaticJointDesc.d \
./Dep/panda/src/physx/physxPulleyJoint.d \
./Dep/panda/src/physx/physxPulleyJointDesc.d \
./Dep/panda/src/physx/physxRay.d \
./Dep/panda/src/physx/physxRaycastHit.d \
./Dep/panda/src/physx/physxRaycastReport.d \
./Dep/panda/src/physx/physxRevoluteJoint.d \
./Dep/panda/src/physx/physxRevoluteJointDesc.d \
./Dep/panda/src/physx/physxScene.d \
./Dep/panda/src/physx/physxSceneDesc.d \
./Dep/panda/src/physx/physxSceneStats2.d \
./Dep/panda/src/physx/physxSegment.d \
./Dep/panda/src/physx/physxShape.d \
./Dep/panda/src/physx/physxShapeDesc.d \
./Dep/panda/src/physx/physxSoftBody.d \
./Dep/panda/src/physx/physxSoftBodyDesc.d \
./Dep/panda/src/physx/physxSoftBodyMesh.d \
./Dep/panda/src/physx/physxSoftBodyMeshDesc.d \
./Dep/panda/src/physx/physxSoftBodyNode.d \
./Dep/panda/src/physx/physxSphere.d \
./Dep/panda/src/physx/physxSphereForceFieldShape.d \
./Dep/panda/src/physx/physxSphereForceFieldShapeDesc.d \
./Dep/panda/src/physx/physxSphereShape.d \
./Dep/panda/src/physx/physxSphereShapeDesc.d \
./Dep/panda/src/physx/physxSphericalJoint.d \
./Dep/panda/src/physx/physxSphericalJointDesc.d \
./Dep/panda/src/physx/physxSpringDesc.d \
./Dep/panda/src/physx/physxTriangleMesh.d \
./Dep/panda/src/physx/physxTriangleMeshDesc.d \
./Dep/panda/src/physx/physxTriangleMeshShape.d \
./Dep/panda/src/physx/physxTriangleMeshShapeDesc.d \
./Dep/panda/src/physx/physxTriggerReport.d \
./Dep/panda/src/physx/physxUtilLib.d \
./Dep/panda/src/physx/physxVehicle.d \
./Dep/panda/src/physx/physxVehicleDesc.d \
./Dep/panda/src/physx/physxWheel.d \
./Dep/panda/src/physx/physxWheelDesc.d \
./Dep/panda/src/physx/physxWheelShape.d \
./Dep/panda/src/physx/physxWheelShapeDesc.d \
./Dep/panda/src/physx/physx_composite.d 


# Each subdirectory must supply rules for building sources it contributes
Dep/panda/src/physx/%.o: ../Dep/panda/src/physx/%.cxx
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C++ Compiler'
	g++ -I"/Users/joda2/workspace/xsilium/Dep" -O2 -g -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


